deploy-to-ecs:
  runs-on: ubuntu-latest
  needs: 
    - build-image-node
    - build-image-react
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Render task definition for Node
      id: taskdef-node
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ecs-task-def.json
        container-name: ${{ env.NODE_CONTAINER_NAME }}
        image: ${{ vars.DOCKER_USERNAME }}/${{ env.NODE_IMAGE_NAME }}:v1.0.${{ github.run_number }}

    - name: Render task definition for React
      id: taskdef-react
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ steps.taskdef-node.outputs.task-definition }}
        container-name: ${{ env.REACT_CONTAINER_NAME }}
        image: ${{ vars.DOCKER_USERNAME }}/${{ env.REACT_IMAGE_NAME }}:v1.0.${{ github.run_number }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.taskdef-react.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
